name: Repository dispatch
on: repository_dispatch
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        run: |
          echo ${{ github.event.client_payload }}
