name: Repository dispath
on:
  repository_dispatch:
    types: [on-demand-test]
jobs: 
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        run: |
          echo Message